version = 0.1
[default.deploy.parameters]
stack_name = "vistocapital-dialer"
resolve_s3 = true
s3_prefix = "vistocapital-dialer"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = false
parameter_overrides = "ConnectInstanceId=\"12345678-1234-1234-1234-123456789012\" ConnectContactFlowId=\"87654321-4321-4321-4321-210987654321\" ConnectQueueId=\"11111111-2222-3333-4444-555555555555\" ValidateProfile=\"False\" CustomerProfilesDomainName=\"vistocapitaltest\" CountryCode=\"1\" ISOCountryCode=\"US\" ConcurrentCalls=\"5\" CallTimeOut=\"3600\" NoCallStatusList=\"No Interest,Do Not Call,Previous Renewal\" SupabaseUrl=\"https://test-project.supabase.co\" SupabaseAnonKey=\"test-anon-key-placeholder\" Environment=\"dev\""
image_repositories = []
