AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Unified Omnichannel Dialer for Amazon Connect - Root Stack

Tags:
  Environment: !Ref Environment

Globals:
  Function:
    Timeout: 60
    MemorySize: 128
    Runtime: python3.9

Parameters:
  ConnectInstanceId:
    Type: String
    AllowedPattern: "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}"
    Description: Amazon Connect Instance ID to use for outbound calls
  ConnectContactFlowId:
    Type: String
    AllowedPattern: "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}"
    Description: Amazon Connect Contact Flow ID to use for outbound calls
  ConnectQueueId:
    Type: String
    AllowedPattern: "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}"
    Description: Amazon Connect Queue ID to use for outbound calls
  ValidateProfile:
    Type: String
    Default: 'True'
    AllowedValues: ["True", "False"]
    Description: Determines whether the function will validate the profile exists or not
  CustomerProfilesDomainName:
    Type: String
    Description: Amazon Connect Customer Profiles Domain Name
  CountryCode:
    Type: Number
    Default: 1
    Description: Country code of destination country
  ISOCountryCode:
    Type: String
    Default: US
    MaxLength: 2
    Description: 2 letter code for country code
  ConcurrentCalls:
    Type: Number
    Default: 5
    Description: Number of calls to be called simultaneously
  CallTimeOut:
    Type: Number
    Default: 3600
    Description: Timeout in seconds for each call
  NoCallStatusList:
    Type: CommaDelimitedList
    Default: No Interest,Do Not Call,Previous Renewal
    Description: Status list for which no call will be made
  SupabaseUrl:
    Type: String
    Description: Supabase project URL (e.g., https://your-project.supabase.co)
  SupabaseAnonKey:
    Type: String
    NoEcho: true
    Description: Supabase anonymous key for API access
  Environment:
    Type: String
    Default: 'prod'
    AllowedValues: ['dev', 'staging', 'prod']
    Description: 'Environment designation for resource tagging'

Resources:
  StorageStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./storage/template.yaml
      Parameters:
        StackName: !Ref AWS::StackName
        StackId: !Ref AWS::StackId
  
  ConfigStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./config/template.yaml
      Parameters:
        StackName: !Ref AWS::StackName
        SupabaseUrl: !Ref SupabaseUrl
        SupabaseAnonKey: !Ref SupabaseAnonKey
  
  IamStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./iam/template.yaml
      Parameters:
        DialingListBucketArn: !GetAtt StorageStack.Outputs.DialingListBucketArn
        ResultsBucketArn: !GetAtt StorageStack.Outputs.ResultsBucketArn
        ActiveDialingTableArn: !GetAtt StorageStack.Outputs.ActiveDialingTableArn
        LeadCacheTableArn: !GetAtt StorageStack.Outputs.LeadCacheTableArn
        SupabaseSecretArn: !GetAtt ConfigStack.Outputs.SupabaseSecretArn

  MessagingStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./messaging/template.yaml
      Parameters:
        StackName: !Ref AWS::StackName
        StackId: !Ref AWS::StackId
        ResultsBucketArn: !GetAtt StorageStack.Outputs.ResultsBucketArn
        KinesisFirehoseDeliveryRoleArn: !GetAtt IamStack.Outputs.KinesisFirehoseDeliveryRoleArn

  LambdasStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./lambdas/template.yaml
      Parameters:
        SsmBasePath: '/connect/unified-dialer'
        UnifiedDialerLambdaRoleArn: !GetAtt IamStack.Outputs.UnifiedDialerLambdaRoleArn
        SupabaseLookupLambdaRoleArn: !GetAtt IamStack.Outputs.SupabaseLookupLambdaRoleArn
        SupabaseSecretArn: !GetAtt ConfigStack.Outputs.SupabaseSecretArn
        LeadCacheTable: !GetAtt StorageStack.Outputs.LeadCacheTable
        ConnectInstanceId: !Ref ConnectInstanceId
        Region: !Ref AWS::Region
        AccountId: !Ref AWS::AccountId

  StateMachineStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./statemachine/template.yaml
      Parameters:
        ParameterDialerStatus: !GetAtt DialerStatusParameter.Name
        GetConfigFunctionArn: !GetAtt LambdasStack.Outputs.PowerDialerGetConfigFunctionArn
        GetContactsFunctionArn: !GetAtt LambdasStack.Outputs.PowerDialerGetContactsFunctionArn
        LookupSupabaseFunctionArn: !GetAtt LambdasStack.Outputs.LookupSupabaseFunctionArn
        DialFunctionArn: !GetAtt LambdasStack.Outputs.PowerDialerDialFunctionArn
        BlasterGetContactsFunctionArn: !GetAtt LambdasStack.Outputs.BlasterGetContactsFunctionArn
        BlasterDialFunctionArn: !GetAtt LambdasStack.Outputs.BlasterDialFunctionArn

  # === SSM Parameters ===
  ContactSourceParameter:
    Type: AWS::SSM::Parameter
    Properties: 
      Name: !Join ['/', ['/connect/unified-dialer', !Ref AWS::StackName,'contact-source']]
      Type: String
      Value: 's3'
  
  DialIndexParameter:
    Type: AWS::SSM::Parameter
    Properties: 
      Name: !Join ['/', ['/connect/unified-dialer', !Ref AWS::StackName,'dialIndex']]
      Type: String
      Value: '0'
  
  DialerStatusParameter:
    Type: AWS::SSM::Parameter
    Properties: 
      Name: !Join ['/', ['/connect/unified-dialer', !Ref AWS::StackName,'activeDialer']]
      Type: String
      Value: 'False'  

  TotalRecordsParameter:
    Type: AWS::SSM::Parameter
    Properties: 
      Name: !Join ['/', ['/connect/unified-dialer', !Ref AWS::StackName,'totalRecords']]
      Type: String
      Value: '0'
  
  ActiveDialingTableParameter:
    Type: AWS::SSM::Parameter
    Properties: 
      Name: !Join ['/', ['/connect/unified-dialer', !Ref AWS::StackName,'table-activedialing']]
      Type: String
      Value: !GetAtt StorageStack.Outputs.ActiveDialingTable

  ContactFlowParameter:
    Type: AWS::SSM::Parameter
    Properties: 
      Name: !Join ['/', ['/connect/unified-dialer', !Ref AWS::StackName,'contactflow']]
      Type: String
      Value: !Ref ConnectContactFlowId

  OutputBucketParameter:
    Type: AWS::SSM::Parameter
    Properties: 
      Name: !Join ['/', ['/connect/unified-dialer', !Ref AWS::StackName,'ResultsBucket']]
      Type: String
      Value: !GetAtt StorageStack.Outputs.ResultsBucket
      
  ConnectIdParameter:
    Type: AWS::SSM::Parameter
    Properties: 
      Name: !Join ['/', ['/connect/unified-dialer', !Ref AWS::StackName,'connectid']]
      Type: String
      Value: !Ref ConnectInstanceId

  QueueParameter:
    Type: AWS::SSM::Parameter
    Properties: 
      Name: !Join ['/', ['/connect/unified-dialer', !Ref AWS::StackName,'queue']]
      Type: String
      Value: !Ref ConnectQueueId

  CountryCodeParameter:
    Type: AWS::SSM::Parameter
    Properties: 
      Name: !Join ['/', ['/connect/unified-dialer', !Ref AWS::StackName,'countrycode']]
      Type: String
      Value: !Ref CountryCode

  ISOCountryCodeParameter:
    Type: AWS::SSM::Parameter
    Properties: 
      Name: !Join ['/', ['/connect/unified-dialer', !Ref AWS::StackName,'isocountrycode']]
      Type: String
      Value: !Ref ISOCountryCode

  ConcurrentCallsParameter:
    Type: AWS::SSM::Parameter
    Properties: 
      Name: !Join ['/', ['/connect/unified-dialer', !Ref AWS::StackName,'concurrentCalls']]
      Type: String
      Value: !Ref ConcurrentCalls

  TimeOutParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join ['/', ['/connect/unified-dialer', !Ref AWS::StackName,'timeOut']]
      Type: String
      Value: !Ref CallTimeOut

  ConcurrencyChangeParameter:
    Type: AWS::SSM::Parameter
    Properties: 
      Name: !Join ['/', ['/connect/unified-dialer', !Ref AWS::StackName,'concurrencyChange']]
      Type: String
      Value: 'False'

  CampaignModeParameter:
    Type: AWS::SSM::Parameter
    Properties: 
      Name: !Join ['/', ['/connect/unified-dialer', !Ref AWS::StackName,'campaignMode']]
      Type: String
      Value: 'power-dialer'
      Description: 'Campaign mode: power-dialer or blaster'

  SupabaseConfigParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join ['/', ['/connect/unified-dialer', !Ref AWS::StackName,'supabase-secret']]
      Type: String
      Value: !GetAtt ConfigStack.Outputs.SupabaseSecretArn
      Description: 'ARN of Supabase credentials secret'

Outputs:
  InputBucket:
    Description: "S3 Bucket for uploading contact lists (CSV format)"
    Value: !GetAtt StorageStack.Outputs.DialingListBucket
    Export:
      Name: !Sub "${AWS::StackName}-InputBucket"

  OutputBucket:
    Description: "S3 Bucket for campaign results and logs"
    Value: !GetAtt StorageStack.Outputs.ResultsBucket
    Export:
      Name: !Sub "${AWS::StackName}-OutputBucket"

  LookupSupabaseFunction:
    Description: "Supabase Lookup Lambda Function ARN for Connect integration"
    Value: !GetAtt LambdasStack.Outputs.LookupSupabaseFunctionArn
    Export:
      Name: !Sub "${AWS::StackName}-SupabaseLookup"

  LeadCacheTable:
    Description: "DynamoDB table for caching lead data"
    Value: !GetAtt StorageStack.Outputs.LeadCacheTable
    Export:
      Name: !Sub "${AWS::StackName}-LeadCache"

  ActiveDialingTable:
    Description: "DynamoDB table for tracking active calls"
    Value: !GetAtt StorageStack.Outputs.ActiveDialingTable
    Export:
      Name: !Sub "${AWS::StackName}-ActiveDialing"

  SupabaseSecret:
    Description: "Secrets Manager secret containing Supabase credentials"
    Value: !GetAtt ConfigStack.Outputs.SupabaseSecretArn
    Export:
      Name: !Sub "${AWS::StackName}-SupabaseSecret"

  ConnectInstanceId:
    Description: "Amazon Connect Instance ID"
    Value: !Ref ConnectInstanceId

  ContactFlowId:
    Description: "Amazon Connect Contact Flow ID"
    Value: !Ref ConnectContactFlowId

  QueueId:
    Description: "Amazon Connect Queue ID"
    Value: !Ref ConnectQueueId

  DeploymentGuide:
    Description: "Next steps for configuration"
    Value: "1. Import contact-flows/UnifiedDialerContactFlow.json to Connect 2. Add Lambda functions to Connect 3. Update Supabase credentials 4. Test with sample-contact-list.csv" 