AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Root stack for ViSto Capital Unified Dialer. Deploys nested stacks for IAM, 
  Storage, Messaging, Lambdas, and Step Functions.

Parameters:
  Environment:
    Type: String
    Default: dev
    Description: The deployment environment (e.g., dev, staging, prod)
  ConnectContactFlowId:
    Type: String
    Description: "ID of the Amazon Connect contact flow"
  ConnectQueueId:
    Type: String
    Description: "ID of the Amazon Connect queue"
  ValidateProfile:
    Type: String
    Description: "Enable/Disable Customer Profiles validation"
  CustomerProfilesDomainName:
    Type: String
    Description: "Amazon Connect Customer Profiles domain name"
  CountryCode:
    Type: String
    Description: "Country code for dialing"
  ISOCountryCode:
    Type: String
    Description: "ISO country code for Amazon Connect"
  ConcurrentCalls:
    Type: String
    Description: "Number of concurrent calls"
  CallTimeOut:
    Type: String
    Description: "Call timeout in seconds"
  NoCallStatusList:
    Type: String
    Description: "List of no-call statuses"
  SupabaseUrl:
    Type: String
    Description: Supabase project URL (e.g., https://your-project.supabase.co)
  SupabaseAnonKey:
    Type: String
    NoEcho: true
    Description: Supabase anonymous key for API access

Resources:
  ConnectInstance:
    Type: 'AWS::Connect::Instance'
    Properties:
      Attributes:
        InboundCalls: true
        OutboundCalls: true
      IdentityManagementType: CONNECT_MANAGED
      InstanceAlias: !Sub 'vistocapital-unified-dialer-${Environment}'

  StorageStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./storage/template.yaml
      Parameters:
        StackName: !Ref AWS::StackName
        StackId: !Ref AWS::StackId
  
  ConfigStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./config/template.yaml
      Parameters:
        StackName: !Ref AWS::StackName
        SupabaseUrl: !Ref SupabaseUrl
        SupabaseAnonKey: !Ref SupabaseAnonKey
  
  IamStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./iam/template.yaml
      Parameters:
        DialingListBucketArn: !GetAtt StorageStack.Outputs.DialingListBucketArn
        ResultsBucketArn: !GetAtt StorageStack.Outputs.ResultsBucketArn
        ActiveDialingTableArn: !GetAtt StorageStack.Outputs.ActiveDialingTableArn
        LeadCacheTableArn: !GetAtt StorageStack.Outputs.LeadCacheTableArn
        SupabaseSecretArn: !GetAtt ConfigStack.Outputs.SupabaseSecretArn

  MessagingStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./messaging/template.yaml
      Parameters:
        StackName: !Ref AWS::StackName
        StackId: !Ref AWS::StackId
        ResultsBucketArn: !GetAtt StorageStack.Outputs.ResultsBucketArn
        KinesisFirehoseDeliveryRoleArn: !GetAtt IamStack.Outputs.KinesisFirehoseDeliveryRoleArn

  LambdasStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./lambdas/template.yaml
      Parameters:
        SsmBasePath: '/connect/unified-dialer'
        UnifiedDialerLambdaRoleArn: !GetAtt IamStack.Outputs.UnifiedDialerLambdaRoleArn
        SupabaseLookupLambdaRoleArn: !GetAtt IamStack.Outputs.SupabaseLookupLambdaRoleArn
        SupabaseSecretArn: !GetAtt ConfigStack.Outputs.SupabaseSecretArn
        LeadCacheTable: !GetAtt StorageStack.Outputs.LeadCacheTable
        ConnectInstanceId: !GetAtt ConnectInstance.Id
        Region: !Ref AWS::Region
        AccountId: !Ref AWS::AccountId
  
  DialerStatusParameter:
    Type: AWS::SSM::Parameter
    Properties: 
      Name: !Sub "/connect/unified-dialer/${AWS::StackName}/activeDialer"
      Type: String
      Value: 'False'  

  StateMachineStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./statemachine/template.yaml
      Parameters:
        ParameterDialerStatus: !Ref DialerStatusParameter
        GetConfigFunctionArn: !GetAtt LambdasStack.Outputs.PowerDialerGetConfigFunctionArn
        GetContactsFunctionArn: !GetAtt LambdasStack.Outputs.PowerDialerGetContactsFunctionArn
        LookupSupabaseFunctionArn: !GetAtt LambdasStack.Outputs.LookupSupabaseFunctionArn
        DialFunctionArn: !GetAtt LambdasStack.Outputs.PowerDialerDialFunctionArn
        BlasterGetContactsFunctionArn: !GetAtt LambdasStack.Outputs.BlasterGetContactsFunctionArn
        BlasterDialFunctionArn: !GetAtt LambdasStack.Outputs.BlasterDialFunctionArn

Outputs:
    UnifiedDialerStateMachineArn:
        Description: "The ARN of the Unified Dialer State Machine"
        Value: !GetAtt StateMachineStack.Outputs.UnifiedDialerStateMachine
        Export:
            Name: !Sub "${AWS::StackName}-UnifiedDialerStateMachineArn"
    ResultsBucket:
        Description: "S3 Bucket for storing call results and recordings"
        Value: !GetAtt StorageStack.Outputs.ResultsBucket
    ConnectInstanceId:
        Description: "The ID of the Amazon Connect instance"
        Value: !GetAtt ConnectInstance.Id
        Export:
            Name: !Sub "${AWS::StackName}-ConnectInstanceId"
    ConnectInstanceArn:
        Description: "The ARN of the Amazon Connect instance"
        Value: !GetAtt ConnectInstance.Arn
        Export:
            Name: !Sub "${AWS::StackName}-ConnectInstanceArn"
    ActiveDialingTable:
        Description: "DynamoDB table for tracking active dialing campaigns"
        Value: !GetAtt StorageStack.Outputs.ActiveDialingTable
    LeadCacheTable:
        Description: "DynamoDB table for caching lead data"
        Value: !GetAtt StorageStack.Outputs.LeadCacheTable
    DialingListBucket:
        Description: "S3 Bucket for uploading dialing lists"
        Value: !GetAtt StorageStack.Outputs.DialingListBucket
    PowerDialerGetConfigFunctionArn:
        Description: "ARN for PowerDialer-getConfig Lambda function"
        Value: !GetAtt LambdasStack.Outputs.PowerDialerGetConfigFunctionArn
    BlasterGetConfigFunctionArn:
        Description: "ARN for Blaster-getConfig Lambda function"
        Value: !GetAtt LambdasStack.Outputs.BlasterGetConfigFunctionArn 